### ISSUE TITLE
How to run calico-mesos by marathon 0.15.2?

### ISSUE THREAD

**Issue by AI-PaaS** [projectcalico/calico-mesos-deployments#15]
I followed the "https://github.com/projectcalico/calico-mesos-deployments/blob/master/docs/UsingCalicoMesos.md" for testing. 
when i run the "https://github.com/projectcalico/calico-mesos-deployments/blob/master/docs/UsingCalicoMesos.md"  int the master, it report "
[root@host-10-1-235-197 mesos]# docker run --net=host calico/calico-mesos-framework 10.1.235.197:5050
Usage:
  calico_framework.py [--master=<MASTER>] [--num-agents=<NUM_AGENTS>] 
  [--default-executor=(true|false)]
"

and then i continue run the example below, the "Launching Tasks" can run a while and quit, the stdout display the container ip. in this part, i want to know how to verify the container network?

in the "Launching Docker Images" part, i can submit the deploy but there are no image run and quit a while. if i delete the cmd, the mesos can not start container and failed.

{
    "id":"/calico-apps",
    "apps": [
        {
            "id": "unified-1",
            "cpus": 0.1,
            "mem": 64.0,
            "ipAddress": {
                "groups": ["my-group-1"]
            },
            "container": {
                "type": "MESOS",
                "mesos": {
                    "image": {
                        "type": "DOCKER",
                        "docker": {
                            "name": "redis:3.0.6"
                        }
                    }
                }
            }
        }
    ]
}
the below is configration from marathon ui  ,you can find there is no image definition:

Current Version - 2016/3/3 下午9:57:50↻ Refresh

✎ Edit
ID
/calico-apps/unified-1
Command
Unspecified
Constraints
Unspecified
Dependencies
Unspecified
Labels
Unspecified
Resource Roles
Unspecified
Container
{
  "type": "MESOS",
  "volumes": [],
  "docker": {
    "image": "",
    "privileged": false,
    "parameters": [],
    "forcePullImage": false
  }
}
CPUs
0.1
Environment
Unspecified
Executor
Unspecified
Health Checks
Unspecified

**Comment by djosborne** [comment]
We don't recommend nor support running the calico-mesos-framework using Marathon, as its a oneshot service. You can run it on any host in your mesos cluster - we recommend using the master.

**Comment by AI-PaaS** [comment]
Sorry for making confuse. I will explain more detail.


I did not run the calico-mesos-framework using Marathon. the above comment has three problem.
     


- run

 the "docker run --net=host calico/calico-mesos-framework <master-ip>:5050" on the mesos master,  it report that "Usage:
calico_framework.py [--master=] [--num-agents=] 
[--default-executor=(true|false)]" and can not run.


-  run the simple task from marathon, i do not know how to verify the container network?


- run the image from marathon, I found that I can not found the image from docker ps, and the configuration of marathon display no image definition

**Comment by djosborne** [comment]
- The reason you're getting the Usage message is that the run command has changed. I cut, built, and pushed a release of `calico/calico-mesos-framework:v0.1.0` which matches the run syntax those docs refer to. However, I would recommend still using `calico/calico-mesos-framework:latest` but modifiying your start flags to match the new syntax: 

`docker run  --net=host calico/calico-mesos-framework --master=10.1.235.197:5050`

Additionally, you may need to set the LIBPROCESS_IP environment variable when running the framework, otherwise it will bind to localhost. Contact me here or on slack for more information on this.

- For the simple marathon task, you can check the task's stdout/stderr in its sandbox to see the result of its call to `ip addr`, which should be a calico IP from the default pool of  192.168.0.0/16. Additionally, you should be able to ping that IP From the slave.

- Running docker images using the MESOS (unified) containerizer doesn't use the docker engine, and thus won't show up in a `docker ps`. Mesos instead unpacks the docker image internally and runs it in Mesos using its own containerizer.

**Comment by AI-PaaS** [comment]
For the simple marathon task, yes. I can get the IP addr from stdout, and I can ping the ip addr in the same slave host, but can not ping it from other slave. 

For the running docker image, Can i use the docker daemon to run?

Thanks.

**Comment by djosborne** [comment]
- What cloud provider are you deploying this on? AWS? Digital Ocean? etc. 
- You can use the docker daemon with calico in mesos. See this guide: https://github.com/projectcalico/calico-mesos-deployments/blob/master/docs/CalicoWithTheDockerContainerizer.md

**Comment by AI-PaaS** [comment]
Thanks thousands. I find the right place finnally
