### ISSUE TITLE
Produce RPM for mesos 0.28.0

### ISSUE THREAD

**Issue by mrares** [projectcalico/calico-mesos-deployments#30]
RPMs for latest release are greatly appreciated

**Comment by djosborne** [comment]
Sorry for the late response. We are working on changes that make net-modules addable to the official mesos RPMs. This change will drastically change our release and build process (for the better!).

I'll work on squeezing our a legacy release of our 0.28 RPMs to unblock you, since the new build process won't be mainline/documented for some time.

**Comment by djosborne** [comment]
@mrares We've changed our releases and will no longer be packaging calico as an RPM. Installing calico agent onto a mesos+netmodules agent is as simple as dropping a few binaries onto an agent configured with netmodules.  Here's information on how:
- https://github.com/projectcalico/calico-containers/blob/master/docs/mesos/ManualInstallCalicoUnifiedContainerizer.md

This requires an agent has netmodules installed and activated. We are pushing Mesosphere to distribute RPMs of Netmodules. In the meantime, you can now manually compile netmodules onto an existing, official Mesos release:
- https://github.com/projectcalico/calico-containers/blob/master/docs/mesos/net-modules/README.md

Do [contact us on Slack](https://calicousers-slackin.herokuapp.com/) if you require further assistance with the build process.
